terms:
  - id: Compromiso con la responsabilidad social
    term: Compromiso con la responsabilidad social
  - id: Equidad social y de género
    term: Equidad social y de género
  - id: Inclusión
    term: Inclusión
  - id: Excelencia
    term: Excelencia
  - id: Innovación social
    term: Innovación social
  - id: Vanguardia
    term: Vanguardia
  - id: Interculturalidad
    term: Interculturalidad
