development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV['FEDORA_URL'] || "http://127.0.0.1:8984/rest" %>
  base_path: /dev
test:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV['FEDORA_TEST_URL'] || "http://127.0.0.1:8986/rest" %>
  base_path: /test
production:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV['FEDORA_URL'] || "http://127.0.0.1:8983/rest" %>
  base_path: /prod
  request: { timeout: 7200, open_timeout: 300 }