---
development:
  user_key:  <%= ENV['IMPORTER_USER_KEY'] || 'rcuellar@colmex.mx'%>
  file_path: <%= ENV['IMPORTER_FILE_PATH'] || 'digital_objects/'%>

test:
  user_key:  <%= ENV['IMPORTER_USER_KEY'] %>
  file_path: <%= ENV['IMPORTER_FILE_PATH'] %>

production:
  user_key:  <%= ENV['IMPORTER_USER_KEY'] %>
  file_path: <%= ENV['IMPORTER_FILE_PATH'] %>
