:queues:
  - default
  - event
  - ingest
development:
  :concurrency: 5
  :timeout: 3
  :logfile: ./log/sidekiq.log
production:
  :concurrency: <%= ENV['SIDEKIQ_CONCURRENCY'] || 20 %>
  :timeout: 5
  :logfile: ./log/sidekiq.log
