:queues:
  - default
  - event
  - ingest
development:
  concurrency: 5
  timeout: 3
  logfile: ./log/sidekiq.log
production:
  concurrency: <%= ENV['SIDEKIQ_CONCURRENCY'] || 2 %>
  timeout:  <%= ENV['SIDEKIQ_TIMEOUT'] || 20 %>
  logfile: ./log/sidekiq.log
